### ISSUE TITLE
bug of preload

### ISSUE THREAD

**Issue by focusonline** [aromig/vue-image-box#5]
Hi, 
   I found a bug when preload image, if images is empty, images[0] will not work, [Error in mounted hook: "TypeError: Cannot read property 'imageUrl' of undefined"] will be rose, can you plz check?
thanks

**Comment by aromig** [comment]
Thank you for catching this!

Should be fixed there. If the `images` array prop is empty, it will not attempt to execute the `preLoad` function.

**Comment by focusonline** [comment]
> Thank you for catching this!
> 
> Should be fixed now. If the `images` array prop is empty, it will not attempt to execute the `preLoad` function.

dear,
   I really do appreciate your quickly response, and I have seen the change, but seems it is not fixed entirely, for example:
```javascript
window.addEventListener("click", e => {
      if (this.imageIndex === 0) {
        this.preLoad(
          this.images[this.images.length - 1].imageUrl,
          this.images[this.imageIndex + 1].imageUrl
        );
      } else if (this.imageIndex === this.images.length - 1) {
        this.preLoad(
          this.images[this.imageIndex - 1].imageUrl,
          this.images[0].imageUrl
        );
      } else { **// here should check the length of images as well?**
        this.preLoad(
          this.images[this.imageIndex - 1].imageUrl,
          this.images[this.imageIndex + 1].imageUrl
        );
      }
    });
    
   if (this.imageIndex > 0) {
        this.preLoad(this.images[this.imageIndex - 1].imageUrl);
      } else { // **and here ?**
        this.preLoad(this.images[this.images.length - 1].imageUrl);
      }
```
I really think every preload invocation should after the validation of images array, else the error will be thrown.
thanks.
